apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZV3hsZUd0eVlYTnViM1l4TXpwbmFIQmZTM0ZaUlVneVRGaFFhMlZxUTFkSGVqUmhSbk5YVHpOd1IySnpkMkZZTkVSR00wRlUifX19
type: kubernetes.io/dockerconfigjson
